spring:
  application:
    name: ungyul-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ungyul}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
